# -*- coding: utf-8 -*-
"""Equipo1_Dataset2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRz7UpBER69HbViXuzVFvHv1lt64LN5R
"""

from sklearn.datasets import load_diabetes
diabetes = load_diabetes()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split, cross_val_score, learning_curve
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error, silhouette_score
from sklearn.inspection import permutation_importance
import seaborn as sns
import pyodbc
# Cargar dataset
diabetes = load_diabetes()

# Convertir a DataFrame
X = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
y = pd.Series(diabetes.target, name="progresion")

df = pd.concat([X, y], axis=1)

df.head()

from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model_lr = LinearRegression()
model_lr.fit(X_train, y_train)

y_pred = model_lr.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print("MSE regresión lineal:", mse)

kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(X)

df["cluster"] = clusters

print(df["cluster"].value_counts())
print("Silhouette score:", silhouette_score(X, clusters))

y_class = pd.qcut(y, q=3, labels=["baja", "media", "alta"])

knn = KNeighborsClassifier(n_neighbors=5)

X_train, X_test, y_train, y_test = train_test_split(X, y_class, test_size=0.2, random_state=42)

knn.fit(X_train, y_train)
acc = knn.score(X_test, y_test)

print("Accuracy K-NN:", acc)

# Crear variable de regresión original
y_reg = pd.Series(diabetes.target, name="progresion")

# Dividir datos SOLO para regresión lineal
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X, y_reg, test_size=0.2, random_state=42
)

# Entrenar regresión lineal
model_lr = LinearRegression()
model_lr.fit(X_train_reg, y_train_reg)

from sklearn.inspection import permutation_importance

result = permutation_importance(
    model_lr, X_test_reg, y_test_reg, n_repeats=10, random_state=42
)

importance_df = pd.DataFrame({
    "feature": X.columns,
    "importance": result.importances_mean
}).sort_values("importance", ascending=False)

print(importance_df)

scores_lr = cross_val_score(model_lr, X, y, cv=5)
scores_knn = cross_val_score(knn, X, y_class, cv=5)

print("CV Regresión Lineal:", scores_lr.mean())
print("CV KNN:", scores_knn.mean())

plt.scatter(y_test, y_pred)
plt.xlabel("Real")
plt.ylabel("Predicción")
plt.title("Regresión lineal – diabetes")
plt.show()

plt.scatter(X["bmi"], X["bp"], c=df["cluster"])
plt.xlabel("Índice de masa corporal (BMI)")
plt.ylabel("Presión sanguínea (BP)")
plt.title("Clusters K-Means – Diabetes")
plt.show()

train_sizes, train_scores, test_scores = learning_curve(
    knn, X, y_class, cv=5
)

plt.plot(train_sizes, train_scores.mean(axis=1), label="train")
plt.plot(train_sizes, test_scores.mean(axis=1), label="test")
plt.legend()
plt.title("Curva de aprendizaje – KNN")
plt.xlabel("Tamaño del entrenamiento")
plt.ylabel("Score")
plt.show()

imp = importance_df.copy()
imp["importance"] = imp["importance"].astype(float)

plt.figure(figsize=(8, 5))
plt.barh(imp["feature"], imp["importance"], color="skyblue")
plt.xlabel("Importancia (Permutation Importance)")
plt.title("Importancia de variables – Diabetes")
plt.gca().invert_yaxis()
plt.grid(axis="x", linestyle="--", alpha=0.4)
plt.show()

plt.bar(["Linear Regression", "KNN"],
        [scores_lr.mean(), scores_knn.mean()])

plt.ylabel("Score promedio CV")
plt.title("Comparación de modelos ML")
plt.show()