# -*- coding: utf-8 -*-
"""Equipo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfngyZuWtVkY3_7T3mJ3zAaWZwjtX7Bh

EQUIPO 1
Dataset 1: heart disease UCI (estadística descriptiva)

*   Christian Albrand Aguirre
*   Samuel Domínguez López
*   Omar Alejandro Elías Banderas
*   Esteban Izhar Torres Hernandez
*   Alan Felipe Escarcega Dominguez
"""

#from sklearn.datasets import fetch_openml
#heart = fetch_openml('heart-disease', version=1)
# 303 pacientes, 14 variables médicas

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "heart.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "johnsmith88/heart-disease-dataset",
  file_path,
)

print("First 5 records:", df.head())

# Export to CSV
df.to_csv("heart.csv", index=False)

# Download CSV
from google.colab import files
files.download("heart.csv")

"""1. Medidas de tendencia central (edad, colesterol, presión arterial)"""

cols = ['age', 'chol', 'trestbps']

central = pd.DataFrame({
    'mean': df[cols].mean(),
    'median': df[cols].median(),
    'mode': df[cols].mode().iloc[0]
})

central

"""2. Medidas de dispersión (todas las variables numéricas)"""

dispersion = df.describe().loc[['std', 'min', 'max']]
dispersion

"""3. Distribución por género y presencia de enfermedad"""

df.groupby(['sex', 'target']).size()

pd.crosstab(df['sex'], df['target'], normalize='index') * 100

"""4. Análisis de correlación entre variables médicas"""

corr = df.corr(numeric_only=True)
corr

corr[corr.abs() > 0.5]

"""5. Identificación de outliers (presión arterial y colesterol)"""

def outliers_iqr(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return series[(series < lower) | (series > upper)]

out_bp = outliers_iqr(df['trestbps'])
out_chol = outliers_iqr(df['chol'])

len_out_bp = len(out_bp)
len_out_chol = len(out_chol)

len_out_bp, len_out_chol